### ISSUE TITLE
dconf-CRITICAL **: unable to create directory '/home/bigbluebutton/.cache/dconf'

### ISSUE THREAD

**Issue by skmohammadi** [bigbluebutton/bbb-install#265]
Hi. I have installed bbb using your script. and these is output of `bbb-conf --status`:
```
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
tomcat7 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]
```

and this is output of `sudo bbb-conf --debug`:
```
-- ERRORS found in /var/log/bigbluebutton/* --
/var/log/bigbluebutton/bbb-web.log:2020-08-25T07:54:48.079Z ERROR o.j.local.office.VerboseProcess -
/var/log/bigbluebutton/bbb-web.log:2020-08-25T07:54:48.080Z ERROR o.j.local.office.VerboseProcess - (process:25791): dconf-CRITICAL **: unable to create directory '/home/bigbluebutton/.cache/dconf': Permission denied.  dconf will not work properly.

...
...
```

what is the problem?

**Comment by rezahmady** [comment]
I have the same problem

**Comment by Peituga** [comment]
I have the same problem too, need to fix since recordings are not being processed.

**Comment by ffdixon** [comment]
Which version have you installed?

**Comment by Peituga** [comment]
Hi @ffdixon I have 2.2.23 version, installed with the sh script.

The first try was unsuccesful, because i had errors while processing recordings and with freeswitch. After that I managed to reinstall and now I only ha e the dconf errors.

Thanks

**Comment by hamzaali4943** [comment]
I have the same problem too

**Comment by ChrisKar96** [comment]
After installation, the directory /home/bigbluebutton/ was not created for me. I solved this issue by running 'mkhomedir_helper bigbluebutton'. This creates the home folder of the bigbluebutton user that is missing. After that, 'systemctl restart bbb-web' and the problem should be solved.

**Comment by mk-hs** [comment]
I'm getting the same error on a newly installed server.
/home/bigbluebutton/ isn't present on any other server I've configured before, so it seems something else is amiss.
I had installed 2.2.24 and it's still present on 2.2.25.

**Comment by ffdixon** [comment]
I think you can ignore those errors -- they don't stop the processing of recordings.

**Comment by praka07** [comment]
i have face same problem and i am not able to land on home page

**Comment by elmokhtar-cheikh** [comment]
Same here! done all the workaround, but it persists.

**Comment by aliraza170** [comment]
my presentation is not uploading, when I click on upload it shows me converting file processing bar, till hours and stuck there, is there any option to fix it or remove this uploading feature from the options, please help me out. thanks

**Comment by nicolasbonnet** [comment]
> `mkhomedir_helper bigbluebutton`

Where do you find this script please ?

**Comment by ffdixon** [comment]
> my presentation is not uploading

Can you try updating to the latest release (2.2.29) and let us know if the problem still persists.

**Comment by goekce** [comment]
I updated from 2.2.28 to 29 and had the same issue, but I am not sure if this problem existed in 28.
https://github.com/bigbluebutton/bbb-install/issues/265#issuecomment-692802688 helped.

**Comment by hoangtk0100** [comment]
After executing ```mkhomedir_helper bigbluebutton```
The error is still there. Because the file in the directory```'/home/bigbluebutton/.cache/dconf'``` does not exist.
So you have to assign permission to access the parent directory
``` chmod 777 /home/bigbluebutton```

**Comment by BoukariOUEDRAOGO** [comment]
Hello,
I have the same problem.
BBB-conf --check is ok
Webcam sharing is ok
Presentation sharing is ok 
Only audio sharing is not ok but shows error message : " Connexion timed out (1006)"
Can some one help please?

Boukari

**Comment by nicolasbonnet** [comment]
Hi, to resolve my problem i have to reinstall the server ....

**Comment by michi-80337** [comment]
I had the same problem after installing 2.2.36 via install.sh

The user "bigbluebutton" will be created by the install script, but its home directory /home/bigbluebutton will not. The script /usr/share/bbb-web/run-prod.sh will then try to create further directories beneath the home, and fail, because the home directory does not exist yet, and the user "bigbluebutton" is not allowed to create it in /home.

My quick and dirty solution was to create the directories /home/bigbluebutton, /home/bigbluebutton/.cache and /home/bigbluebutton/.cache/dconf by hand as root:

    mkdir /home/bigbluebutton /home/bigbluebutton/.cache /home/bigbluebutton/.cache/dconf
    chown -R bigbluebutton:bigbluebutton /home/bigbluebutton
    chmod -R o-rwx,g=u,g-w /home/bigbluebutton

The commands might differ slightly on your system, but you get the idea. In my view, giving mode 777 to directories should be avoided for security reasons.

CU, Michi

**Comment by bbbondemand** [comment]
I had same problem, fairly new install 2.236 with bbb-install.sh - meetings closed afer about 7 minutes apparently due to this problem.  Recreating the folders as shown by @michi-80337 worked for me.

**Comment by ffdixon** [comment]
> meetings closed afer about 7 minutes apparently due to this problem.  

This error shouldn't be related to meetings closing.  Do you see anything in the `/var/log/bigbluebutton/bbb-web.log` related to the meeting closing.  Did you get a specific message when the meeting closed?

**Comment by bbbondemand** [comment]
Really sorry Fred - you are right it was not the cause of my problem.  

The script from @michi-80337 stopped the dconf- errors but were unrelated to my meeting shutting down (which is only happening via an intergration created meeting - not mconf so I will dig deeper on that and raise seperate ticket or question on the group if I get stuck!)

**Comment by hex-m** [comment]
User creation happens in `bbb-record-core.preinst`
```
addGroup bigbluebutton ""
addUser bigbluebutton "" bigbluebutton /home/bigbluebutton "bigbluebutton" "/bin/false"
```

The [documentation](https://wiki.debian.org/AccountHandlingInMaintainerScripts) mentions it should be something like `adduser --system --group bigbluebutton`. That should add the user, group and home directory and set the shell to `/bin/false`.

I have that problem on my BBB-Servers. The only "specialty" I can think of is that I ran `bbb-install.sh` as root, not using `sudo`.

I also checked my `bbb 2.3.1` system and there `/home/bigbluebutton` is missing too.

**Comment by michi-80337** [comment]
There are multiple packages that create the user if it doesn't exist yet. I found it in bbb-apps-akka.postinst, bbb-fsesl-akka.postinst, bbb-record-core.preinst, and in bbb-transcode-akka.postinst. Which one is actually used, depends on the installation order of these packages.

addUser() is a shell function defined in the install scripts, and the function delegates the actual work to the useradd system tool:

    [...]
    if [ -z "$uid" ]; then
        uid_flags=""
    else
        uid_flags="--uid $uid"
    fi
    [...]
    if ! getent passwd | grep -q "^$user:";
    then
        echo "Creating system user: $user in $group with $descr and shell $shell"
        useradd $uid_flags --gid $group -r --shell $shell -c "$descr" $user
    fi
    [...]

The -r switch is equivalent to the --system switch. The man page for useradd states:

    [...]
    -r, --system
        Create a system account.

        System users will be created with no aging information in
        /etc/shadow, and their numeric identifiers are chosen in the
        SYS_UID_MIN-SYS_UID_MAX range, defined in /etc/login.defs, instead
        of UID_MIN-UID_MAX (and their GID counterparts for the creation of
        groups).

        Note that useradd will not create a home directory for such an
        user, regardless of the default setting in /etc/login.defs
        (CREATE_HOME). You have to specify the -m options if you want a
        home directory for a system account to be created.
    [...]

The manpage further tells that -m and --create-home are equivalent. Now let's have a deeper look into bbb-record-core.preinst, because the userAdd function looks a little bit different there:

    [...]
        if [ -z "$uid" ]; then
            uid_flags=""
        else
            uid_flags="--uid $uid"
        fi
        if [ -z "$4" ]; then
            home_flags="--no-create-home"
        else
            home_flags="-d $4"
        fi
    [...]
        if ! getent passwd | grep -q "^$user:";
        then
            # echo "Creating system user: $user in $group with $descr and shell $shell"
            useradd $uid_flags --gid $group $home_flags --system --shell $shell -c "$descr" $user
        fi
    [...]

There is no -m switch to create the directory. Hence no directory is created.

The -d switch used in the function just controls the home directory field in /etc/passwd:

    [...]
    -d, --home-dir HOME_DIR
        The new user will be created using HOME_DIR as the value for the
        user's login directory. The default is to append the LOGIN name to
        BASE_DIR and use that as the login directory name. The directory
        HOME_DIR does not have to exist but will not be created if it is
        missing.
    [...]

**Comment by schrd** [comment]
is this issue still relevant? Libreoffice is running in a container since BBB 2.3. Please test with the latest 2.4 release.
